version: '3.6'

services:
  tomatoclock-server:
    image: commserver
    ports:
      - 10088:3000
    container_name: commserver
    volumes:
      - ./data:/home/myapp/data
      - ./conf:/home/myapp/conf
      - /etc/localtime:/etc/localtime:ro